apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  labels:
    app: postgres
data:
  create-dbs.sql: |
    CREATE DATABASE cars;
    CREATE DATABASE rental;
    CREATE DATABASE payment;
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE cars TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE rental TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE payment TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO postgres;