apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    app: keycloak
data:
  car-rental-realm.json: |
    {
      "id": "car-rental",
      "realm": "car-rental",
      "enabled": true,
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "Regular user"
          }
        ]
      },
      "users": [
        {
          "username": "test",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "test",
              "temporary": false
            }
          ],
          "realmRoles": ["user"]
        }
      ],
      "clients": [
        {
          "clientId": "rental-client",
          "enabled": true,
          "publicClient": false,
          "secret": "my-super-secret",
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "serviceAccountsEnabled": false,
          "authorizationServicesEnabled": false,
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "protocol": "openid-connect",
          "attributes": {
            "access.token.lifespan": "3600"
          }
        }
      ]
    }