apiVersion: v2
name: infrastructure
description: Infrastructure via OCI
type: application
version: 0.1.0
appVersion: "1.0.0"


dependencies:
  - name: postgresql
    version: 12.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: postgresql

  - name: rabbitmq
    version: 12.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: rabbitmq

  - name: keycloak
    version: 16.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: keycloak